### ISSUE TITLE
Fix CSS bugs

### ISSUE THREAD

**Issue by vwinstea** [hack4impact-calpoly/city-farm-slo#68]
A couple of CSS bugs I noticed that we should get fixed:

- [x] #80
![image](https://user-images.githubusercontent.com/32073638/153966725-5cc97f54-7484-482a-9a46-0ca831937348.png)
- [x] #81
- [x] #82
![image](https://user-images.githubusercontent.com/32073638/153961954-bd1a1971-e894-4b75-8932-009076f5d272.png)
- [x] #83
![image](https://user-images.githubusercontent.com/32073638/153962143-5d5bf5ea-301f-475d-b615-8ad678f83239.png)

I'd highly recommend using your browser's responsive design mode to test these bugs on a variety of screen sizes. Don't worry about mobile sizes yet, but please do check smaller laptop screen sizes.

**Comment by adellevo** [comment]
Event data is somehow not loading for me at all? I pulled on main to get the latest changes too so idk why this is happening
<img width="626" alt="Screen Shot 2022-02-21 at 1 38 37 PM" src="https://user-images.githubusercontent.com/22452107/155029156-aa4c2dad-d307-456b-83e9-8372d98b68b8.png">

**Comment by vwinstea** [comment]
Sorry about that! It looks like the Pull Request that added the event card (PR #67) to that page never got merged in. For that sub-task could you make your commit to the `hannah-add-eventCard` branch?

**Comment by adellevo** [comment]
Yep! Just added the other changes to the hannah-add-eventCard branch. When the browser width hits a certain breakpoint, the layout should look like this: <img width="550" alt="Screen Shot 2022-02-27 at 11 17 44 AM" src="https://user-images.githubusercontent.com/22452107/155896577-9f846fd9-e3a0-49bc-8747-cd581c422d2f.png">

**Comment by vwinstea** [comment]
Looking good! Thanks for adding that vertical configuration, it will certainly make our job a lot easier if we adapt this website for phones. Quick question -- have you tackled the multiline event title/slots issue yet? If you have which PR should I look at?

**Comment by adellevo** [comment]
> Looking good! Thanks for adding that vertical configuration, it will certainly make our job a lot easier if we adapt this website for phones. Quick question -- have you tackled the multiline event title/slots issue yet? If you have which PR should I look at?

I think it's in the `hannah-add-eventCard` branch — the vertical configuration also has a minimum size set to make sure the event box never gets to a size where the multiline thing occurs. Users do have to scroll to view the full form though, and idk if that's okay. Lmk if you'd prefer to have it where no one has to scroll!

**Comment by vwinstea** [comment]
PR #75 and PR #78 ended up having a lot of merge conflicts, so unfortunately some of your work ended up getting lost in the process. I think I was able to save most of it, but I was still seeing the multi line issue on the Event Card and the vertical sign up form display got lost in the mix as well. If you could take a look at those two things sometime before finals, I'd really appreciate it. Sorry to make you repeat some work, it was totally not your fault!
